// This file can be included several times.

#ifndef MACRO_CONFIG_INT
#error "The config macros must be defined"
#define MACRO_CONFIG_INT(Name, ScriptName, Def, Min, Max, Save, Desc) ;
#define MACRO_CONFIG_COL(Name, ScriptName, Def, Save, Desc) ;
#define MACRO_CONFIG_STR(Name, ScriptName, Len, Def, Save, Desc) ;
#endif

// Frozen skin
MACRO_CONFIG_STR(BcFrozenSkin, bc_frozen_skin, 24, "", CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_INSENSITIVE, "Skin to show on frozen players, empty keeps the default behavior")
MACRO_CONFIG_INT(BcFrozenSkinDarken, bc_frozen_skin_darken, 0, 0, 70, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Darken the frozen skin override (0 - normal, 70 - max darkened)")

// SettingsTabs
MACRO_CONFIG_INT(BcBestClientSettingsTabs, bc_bestclient_settings_tabs, 0, 0, 65536, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bit flags to disable BestClient settings tabs") // bestclient

// Chat QoL
MACRO_CONFIG_INT(BcSilentTyping, bc_silent_typing, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide PLAYERFLAG_CHATTING from others while typing")
MACRO_CONFIG_INT(BcChatAltCommandLayout, bc_chat_alt_command_layout, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Interpret slash chat commands typed in the Russian keyboard layout")
MACRO_CONFIG_INT(BcChatMessageActions, bc_chat_message_actions, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable reply/copy message menu on chat messages")
MACRO_CONFIG_INT(BcNotifySavesOnMap, bc_notify_saves_on_map, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Notify in chat when the current map has team saves")

// Chat Filter
MACRO_CONFIG_INT(BcChatOnlyTagsAndWhispers, bc_chat_only_tags_and_whispers, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show only highlighted and private chat messages")

// Translate
MACRO_CONFIG_STR(BcTranslateIncomingSource, bc_translate_incoming_source, 16, "auto", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Source language for incoming chat translation")
MACRO_CONFIG_STR(BcTranslateIncomingIgnoreLanguages, bc_translate_incoming_ignore_languages, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Source languages that should not be auto-translated")
MACRO_CONFIG_STR(BcTranslateOutgoingSource, bc_translate_outgoing_source, 16, "auto", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Source language for outgoing chat translation")
MACRO_CONFIG_STR(BcTranslateOutgoingTarget, bc_translate_outgoing_target, 16, "en", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Target language for outgoing chat translation")
MACRO_CONFIG_INT(BcTranslateOutgoingStripPunctuation, bc_translate_outgoing_strip_punctuation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Remove apostrophes from translated outgoing chat messages")
MACRO_CONFIG_INT(BcTranslateShiftClickTarget, bc_translate_shift_click_target, 2, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shift+click translate icon toggles: 0 others, 1 yours, 2 both")

// Casino
MACRO_CONFIG_INT(BcCasinoBalance, bc_casino_balance, 500, 0, 9999999, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Casino game balance in dollars")
MACRO_CONFIG_INT(BcCasinoLastClaim, bc_casino_last_claim, 0, 0, 2147483647, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Unix timestamp of last casino free claim")

// Auto update
MACRO_CONFIG_INT(BcAutoUpdate, bc_auto_update, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically download and apply updates on startup")

// Twitch chat integration
MACRO_CONFIG_STR(BcTwitchChatNick, bc_twitch_chat_nick, 64, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Twitch channel nick for chat integration")

// Aspect ratio
MACRO_CONFIG_INT(BcCustomAspectRatioMode, bc_custom_aspect_ratio_mode, -1, -1, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aspect ratio mode (-1=legacy auto, 0=off, 1=preset, 2=custom)")
MACRO_CONFIG_INT(BcCustomAspectRatioApplyMode, bc_custom_aspect_ratio_apply_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aspect ratio apply mode (0=game only, 1=full, 2=game no hud)")
MACRO_CONFIG_INT(BcCustomAspectRatio, bc_custom_aspect_ratio, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aspect ratio value x100 (0=off, presets: 125=5:4, 133=4:3, 150=3:2, custom: 100-1000)")
MACRO_CONFIG_INT(BcCustomAspectRatioNum, bc_custom_aspect_ratio_num, 0, 0, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio numerator (width), 0=unset")
MACRO_CONFIG_INT(BcCustomAspectRatioDen, bc_custom_aspect_ratio_den, 0, 0, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio denominator (height), 0=unset")

// Visuals QoL
MACRO_CONFIG_INT(BcEntitiesRounding, bc_entities_rounding, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Entity contour rounding in percent (0 = square, 100 = circle)")
MACRO_CONFIG_INT(BcEntitiesRoundingMode, bc_entities_rounding_mode, 2, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Entity rounding corners (0 = outer, 1 = inner, 2 = both)")
MACRO_CONFIG_INT(BcShowRealHitbox, bc_show_real_hitbox, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a dot at the center of your real hitbox")
MACRO_CONFIG_COL(BcShowRealHitboxColor, bc_show_real_hitbox_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Color of the real hitbox center dot")
MACRO_CONFIG_INT(BcShowhudDummyCoordIndicator, bc_showhud_dummy_coord_indicator, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show player-below indicator when aligned above another player")
MACRO_CONFIG_INT(BcShowCorrectCheckpoint, bc_show_correct_checkpoint, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show current tele checkpoint in movement information")
MACRO_CONFIG_INT(BcShowPointsInTab, bc_show_points_in_tab, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show player points in the scoreboard on DDNet, EGO and Legit Network servers")
MACRO_CONFIG_INT(BcShowSpectatorNames, bc_show_spectator_names, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show spectator nicknames in the spectator count HUD")
MACRO_CONFIG_INT(BcShowVotePercentage, bc_show_vote_percentage, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show yes/no vote percentages on the vote HUD")
MACRO_CONFIG_INT(BcScoreboardScale, bc_scoreboard_scale, 100, 50, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scoreboard scale in percent, independent of UI scale")
MACRO_CONFIG_INT(BcWheelScale, bc_wheel_scale, 100, 50, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bind/emote wheel scale in percent, independent of UI scale")
MACRO_CONFIG_INT(UiScale, ui_scale, 100, 50, 110, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Global UI scale in percent")

// Discord RPC
MACRO_CONFIG_INT(BcDiscordRPC, bc_discord_rpc, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable bestclient discord rpc (restart requires)")

// Physic Balls
MACRO_CONFIG_STR(BcPhysicBallsSkin, bc_physic_balls_skin, 24, "volleyball", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Base skin for physic balls")
MACRO_CONFIG_INT(BcPhysicBallsSpawnCount, bc_physic_balls_spawn_count, 1, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How many physic balls to spawn per action")

// Cursor trail
MACRO_CONFIG_INT(BcCursorTrail, bc_cursor_trail, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable cursor trail")
MACRO_CONFIG_INT(BcCursorTrailMode, bc_cursor_trail_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cursor trail mode (0=cursor, 1=custom)")
MACRO_CONFIG_STR(BcCursorTrailTrailImage, bc_cursor_trail_trail_image, IO_MAX_PATH_LENGTH, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Path to the custom cursor trail image")
MACRO_CONFIG_INT(BcCursorTrailTrailSize, bc_cursor_trail_trail_size, 70, 10, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cursor trail size")
MACRO_CONFIG_INT(BcCursorTrailNumberOfFrames, bc_cursor_trail_number_of_frames, 5, 1, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Number of cursor trail frames")
MACRO_CONFIG_INT(BcCursorTrailOpacity, bc_cursor_trail_opacity, 80, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cursor trail opacity")
MACRO_CONFIG_INT(BcCursorTrailSamplingFps, bc_cursor_trail_sampling_fps, 120, 24, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cursor trail sampling frequency")
MACRO_CONFIG_INT(BcCursorTrailDisableMovement, bc_cursor_trail_disable_movement, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep cursor trail stable when the player moves")

// Gameplay QoL
MACRO_CONFIG_INT(TcEgoTilesAntiLag, tc_ego_tiles_antilag, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Predict Ego-Tiles freeze/unfreeze quads like the server")
MACRO_CONFIG_INT(BcConfirmQuit, bc_confirm_quit, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a confirmation dialog before quitting the game")
MACRO_CONFIG_INT(BcCinematicCamera, bc_cinematic_camera, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable smooth cinematic camera movement in spectator freeview")
MACRO_CONFIG_INT(BcCinematicCameraStrength, bc_cinematic_camera_strength, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strength of cinematic camera smoothing (0 = mild, 100 = strong)")
MACRO_CONFIG_INT(BcSpecMovedNotify, bc_spec_moved_notify, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show 'moved in game' warning when someone hooks/hits your character while you are in spectator")
MACRO_CONFIG_STR(BcSpecMovedNotifyText, bc_spec_moved_notify_text, 128, "you moved in game", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Text shown when someone hooks/hits your character while you are in spectator")
MACRO_CONFIG_INT(BcAutoTeamLock, bc_auto_team_lock, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically lock your team after joining it")
MACRO_CONFIG_INT(BcAutoTeamLockDelay, bc_auto_team_lock_delay, 5, 0, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delay before auto-locking team after joining, in seconds")
MACRO_CONFIG_INT(BcExtendZoom, bc_extend_zoom, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use 0.5 zoom steps instead of 1 for finer scroll zoom (10, 9.5, 9, 8.5 ...)")
MACRO_CONFIG_INT(BcBetterSpectate, bc_better_spectate, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Replace say /pause bind (default Q) with +specpause radio menu")
MACRO_CONFIG_INT(BcSpecPauseShowDelay, bc_spec_pause_show_delay, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delay before the spec pause radio becomes visible (ms)")

// CameraDrift (demo playback only)
MACRO_CONFIG_INT(BcCameraDrift, bc_camera_drift, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable camera drift during demo playback")
MACRO_CONFIG_INT(BcCameraDriftAmount, bc_camera_drift_amount, 50, 1, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of camera drift during demo playback")
MACRO_CONFIG_INT(BcCameraDriftSmoothness, bc_camera_drift_smoothness, 20, 1, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smoothness of camera drift during demo playback")
MACRO_CONFIG_INT(BcCameraDriftReverse, bc_camera_drift_reverse, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Reverse camera drift direction during demo playback")
// Freeview Numpad Camera (spectator/demo playback)
MACRO_CONFIG_INT(BcFreeviewNumpad, bc_freeview_numpad, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable numpad camera movement in freeview/spectator mode")
MACRO_CONFIG_INT(BcFreeviewSpeed, bc_freeview_speed, 180, 1, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeview camera movement speed")
MACRO_CONFIG_INT(BcFreeviewSmoothness, bc_freeview_smoothness, 25, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeview camera smoothness (acceleration)")
// DynamicFov (demo playback only)
MACRO_CONFIG_INT(BcDynamicFov, bc_dynamic_fov, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable dynamic FOV during demo playback")
MACRO_CONFIG_INT(BcDynamicFovAmount, bc_dynamic_fov_amount, 50, 1, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of dynamic FOV during demo playback")
MACRO_CONFIG_INT(BcDynamicFovSmoothness, bc_dynamic_fov_smoothness, 20, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smoothness of dynamic FOV during demo playback")

// Quick binds (45 degrees / small sens)
MACRO_CONFIG_INT(BcPrevMouseMaxDistance45Degrees, bc_prev_mouse_max_distance_45_degrees, 400, 0, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_INSENSITIVE, "Previous maximum cursor distance for 45 degrees")
MACRO_CONFIG_INT(BcPrevInpMousesens45Degrees, bc_prev_inp_mousesens_45_degrees, 200, 1, 1000000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Previous mouse sensitivity for 45 degrees")
MACRO_CONFIG_INT(BcToggle45Degrees, bc_toggle_45_degrees, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use toggle mode for 45 degrees bind")
MACRO_CONFIG_INT(BcPrevInpMousesensSmallSens, bc_prev_inp_mousesens_small_sens, 200, 1, 1000000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Previous mouse sensitivity for small sens")
MACRO_CONFIG_INT(BcToggleSmallSens, bc_toggle_small_sens, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use toggle mode for small sens bind")

// Inputs
MACRO_CONFIG_INT(BcInputs, bc_inputs, 0, 0, 6, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Input prediction mode (0 = off, 1 = fast, 2 = best, 3 = saiko, 4 = delta, 5 = f, 6 = cloud)")
MACRO_CONFIG_INT(BcBestInputAmount, bc_best_input_amount, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input prediction amount in 0.01 ticks")
MACRO_CONFIG_INT(BcBestInputSmoothing, bc_best_input_smoothing, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input smoothing amount (0-100%)")
MACRO_CONFIG_INT(BcBestInputLatencyComp, bc_best_input_latency_comp, 0, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input latency compensation (0-50%)")
MACRO_CONFIG_INT(BcBestInputInterpolation, bc_best_input_interpolation, 1, 1, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input interpolation mode (1 = linear, 2 = cubic, 3 = smooth)")
MACRO_CONFIG_INT(BcBestInputOthers, bc_best_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply best input to other tees")
MACRO_CONFIG_INT(BcSaikoInputAmount, bc_saiko_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Saiko input amount in 0.01 ticks")
MACRO_CONFIG_INT(BcSaikoInputOthers, bc_saiko_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Saiko input to other tees")
MACRO_CONFIG_INT(BcDeltaInputAmount, bc_delta_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delta input amount in 0.01 ticks")
MACRO_CONFIG_INT(BcDeltaInputOthers, bc_delta_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply delta input to other tees")
MACRO_CONFIG_INT(BcFInputAmount, bc_f_input_amount, 0, 0, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "F input amount in 0.001-tick units (0=off, 1000=1.000 ticks, max 5000=5.000 ticks)")
MACRO_CONFIG_INT(BcFInputOthers, bc_f_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply F input to other tees")
MACRO_CONFIG_INT(BcCloudInputAmount, bc_cloud_input_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cloud input amount in 0.01 ticks")
MACRO_CONFIG_INT(BcCloudInputOthers, bc_cloud_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply cloud input to other tees")
MACRO_CONFIG_INT(BcAutoMargin, bc_auto_margin, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto margin")

// MuteOthers
MACRO_CONFIG_INT(BcMuteOthersHook, bc_mute_others_hook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute hook sounds of other players")
MACRO_CONFIG_INT(BcMuteOthersHammer, bc_mute_others_hammer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute hammer sounds of other players")
MACRO_CONFIG_INT(BcMuteOthersAirJump, bc_mute_others_airjump, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute double jump sounds of other players")

// Gores mode
MACRO_CONFIG_INT(BcGoresMode, bc_gores_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Entity-like gores mode")
MACRO_CONFIG_INT(BcGoresModeDisableIfWeapons, bc_gores_mode_disable_weapons, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable gores mode when holding shotgun, grenade or laser")

// Fast Actions
MACRO_CONFIG_INT(BcFastActions, bc_fast_actions, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable the Fast Actions quick command selector")

// Snap Tap
MACRO_CONFIG_INT(BcSnapTap, bc_snap_tap, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Snap Tap for opposite left/right inputs")
MACRO_CONFIG_INT(BcSnapTapDelay, bc_snap_tap_delay, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Snap Tap direction switch delay in milliseconds (0 = off)")

// Jelly tee
MACRO_CONFIG_INT(BcJellyTee, bc_jelly_tee, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable jelly tee deformation")
MACRO_CONFIG_INT(BcJellyTeeOthers, bc_jelly_tee_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply jelly tee deformation to other players")
MACRO_CONFIG_INT(BcJellyTeeStrength, bc_jelly_tee_strength, 500, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strength of jelly tee deformation")
MACRO_CONFIG_INT(BcJellyTeeDuration, bc_jelly_tee_duration, 30, 1, 80, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Duration of jelly tee deformation")

// Gradient
MACRO_CONFIG_INT(BcNameplateGradient, bc_nameplate_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient player nicknames")
MACRO_CONFIG_INT(BcNameplateGradientClan, bc_nameplate_gradient_clan, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient player clan tags")
MACRO_CONFIG_INT(BcNameplateGradientMode, bc_nameplate_gradient_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient mode (0 = skin colors, 1 = custom, 2 = rainbow)")
MACRO_CONFIG_INT(BcNameplateGradientColorCount, bc_nameplate_gradient_color_count, 2, 2, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Number of custom gradient colors")
MACRO_CONFIG_COL(BcNameplateGradientColor1, bc_nameplate_gradient_color1, 0xFF3366FFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom gradient color 1")
MACRO_CONFIG_COL(BcNameplateGradientColor2, bc_nameplate_gradient_color2, 0xFF66CCFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom gradient color 2")
MACRO_CONFIG_COL(BcNameplateGradientColor3, bc_nameplate_gradient_color3, 0xFF33FF99U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom gradient color 3")
MACRO_CONFIG_COL(BcNameplateGradientColor4, bc_nameplate_gradient_color4, 0xFFFFCC33U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom gradient color 4")
MACRO_CONFIG_INT(BcNameplateGradientSkin, bc_nameplate_gradient_skin, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply gradient colors to player skin body and feet")
MACRO_CONFIG_INT(BcNameplateGradientEverything, bc_nameplate_gradient_everything, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply gradient to all rendered text")
MACRO_CONFIG_INT(BcNameplateGradientAnimateSpeed, bc_nameplate_gradient_animate_speed, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speed of the animated gradient sweep, in percent")
MACRO_CONFIG_INT(BcNameplateGradientTarget, bc_nameplate_gradient_target, 2, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Who the gradient applies to (0 = own, 1 = others, 2 = all)")

// Flying name plates
MACRO_CONFIG_INT(BcFlyingNamePlates, bc_flying_name_plates, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render name plates like flying kites attached to players")
MACRO_CONFIG_INT(BcFlyingNamePlatesHideLine, bc_flying_name_plates_hide_line, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide the line between players and flying name plates")
MACRO_CONFIG_INT(BcFlyingNamePlatesLift, bc_flying_name_plates_lift, 28, 0, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Extra vertical lift for flying name plates")
MACRO_CONFIG_INT(BcFlyingNamePlatesDrag, bc_flying_name_plates_drag, 52, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How far flying name plates trail behind movement")
MACRO_CONFIG_INT(BcFlyingNamePlatesFollow, bc_flying_name_plates_follow, 40, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How quickly flying name plates catch up to their target position")

// 3D particles
MACRO_CONFIG_INT(Bc3dParticles, bc_3d_particles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesType, bc_3d_particles_type, 1, 1, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Type of 3D particles. 1 = Cube, 2 = Heart, 3 = Mixed")
MACRO_CONFIG_INT(Bc3dParticlesDensity, bc_3d_particles_density, 50, 1, 600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Density of 3D particles on the map")
MACRO_CONFIG_INT(Bc3dParticlesSizeMax, bc_3d_particles_size_max, 8, 2, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum size of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesSpeed, bc_3d_particles_speed, 18, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Base speed of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesDepth, bc_3d_particles_depth, 300, 10, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Depth range for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesAlpha, bc_3d_particles_alpha, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Alpha of 3D particles (1-100)")
MACRO_CONFIG_INT(Bc3dParticlesPushRadius, bc_3d_particles_push_radius, 120, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player push radius for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesPushStrength, bc_3d_particles_push_strength, 120, 0, 2000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player push strength for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesCollide, bc_3d_particles_collide, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "3D particles collide with each other")
MACRO_CONFIG_INT(Bc3dParticlesViewMargin, bc_3d_particles_view_margin, 200, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Margin outside view before 3D particles disappear")
MACRO_CONFIG_INT(Bc3dParticlesColorMode, bc_3d_particles_color_mode, 1, 1, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color mode for 3D particles. 1 = Custom, 2 = Random")
MACRO_CONFIG_COL(Bc3dParticlesColor, bc_3d_particles_color, 4294967295, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Color of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesGlow, bc_3d_particles_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable 3D particles glow")

// Weapon Glow Visuals (Laser, Shotgun, Rocket)
MACRO_CONFIG_INT(BcLaserGlow, bc_laser_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Laser Glow visual effect")
MACRO_CONFIG_INT(BcLaserGlowPower, bc_laser_glow_power, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser Glow power/intensity (0-100)")
MACRO_CONFIG_INT(BcLaserGlowMode, bc_laser_glow_mode, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser Glow mode: 0=Classic, 1=Prism, 2=Pulse, 3=Crystal")
MACRO_CONFIG_COL(BcLaserGlowColor, bc_laser_glow_color, 5635840, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Laser Glow custom color")

MACRO_CONFIG_INT(BcShotgunGlow, bc_shotgun_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Shotgun Glow visual effect")
MACRO_CONFIG_INT(BcShotgunGlowPower, bc_shotgun_glow_power, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun Glow power/intensity (0-100)")
MACRO_CONFIG_INT(BcShotgunGlowMode, bc_shotgun_glow_mode, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun Glow mode: 0=Classic, 1=Prism, 2=Pulse, 3=Crystal")
MACRO_CONFIG_COL(BcShotgunGlowColor, bc_shotgun_glow_color, 5635840, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Shotgun Glow custom color")

MACRO_CONFIG_INT(BcRocketGlow, bc_rocket_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Rocket/Grenade Glow visual effect")
MACRO_CONFIG_INT(BcRocketGlowPower, bc_rocket_glow_power, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rocket Glow power/intensity (0-100)")
MACRO_CONFIG_INT(BcRocketGlowMode, bc_rocket_glow_mode, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rocket Glow mode: 0=Classic, 1=Prism, 2=Pulse, 3=Crystal")
MACRO_CONFIG_COL(BcRocketGlowColor, bc_rocket_glow_color, 2555648, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Rocket Glow custom color")

// Meme Nuke Rocket Explosion & Screen Shake
MACRO_CONFIG_INT(BcMemeNukeExplosion, bc_meme_nuke_explosion, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable meme mega nuclear explosion on rocket impact")
MACRO_CONFIG_INT(BcMemeNukeShake, bc_meme_nuke_shake, 100, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Screen shake intensity for nuke rocket explosion (0-200%)")
MACRO_CONFIG_INT(BcMemeNukeScale, bc_meme_nuke_scale, 100, 20, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scale of the meme nuke explosion (20-300%)")

// Assets (cursor / arrow / audio)
MACRO_CONFIG_STR(ClAssetCursor, cl_asset_cursor, 50, "default", CFGFLAG_CLIENT | CFGFLAG_SAVE, "The asset for cursor")
MACRO_CONFIG_STR(ClAssetArrow, cl_asset_arrow, 50, "default", CFGFLAG_CLIENT | CFGFLAG_SAVE, "The asset for arrow")
MACRO_CONFIG_STR(SndPack, snd_pack, 64, "default", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Sound pack")

// Profile assets
MACRO_CONFIG_INT(BcProfileAssets, bc_profile_assets, 0, 0, 511, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of asset types to save/load in profiles")

// Better preview
MACRO_CONFIG_INT(BcBetterPreview, bc_better_preview, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Better preview")

// Media background
MACRO_CONFIG_INT(BcMenuMediaBackground, bc_menu_media_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable custom media background in offline menus")
MACRO_CONFIG_INT(BcGameMediaBackground, bc_game_media_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable custom media background in game background rendering")
MACRO_CONFIG_STR(BcMenuMediaBackgroundPath, bc_menu_media_background_path, IO_MAX_PATH_LENGTH, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Path to the custom menu media background file")
MACRO_CONFIG_INT(BcGameMediaBackgroundOffset, bc_game_media_background_offset, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How much the custom media background is fixed to the map when rendering the in-game background")

// Menu UI
MACRO_CONFIG_INT(BcMenuUiStyle, bc_menu_ui_style, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Menu UI style (0 = legacy, 1 = Better UI)")
MACRO_CONFIG_INT(BcMenuUiNewCheckbox, bc_menu_ui_new_checkbox, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use better checkbox style when Better UI is enabled")
MACRO_CONFIG_INT(BcMenuUiNewScrollbar, bc_menu_ui_new_scrollbar, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use better scrollbar style when Better UI is enabled")
MACRO_CONFIG_INT(BcMenuUiNewTabOption, bc_menu_ui_new_tab_option, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use better settings tab navigation when Better UI is enabled")
MACRO_CONFIG_INT(BcMenuUiTabSide, bc_menu_ui_tab_side, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Settings tabs side when Better tab option is on (0 = left, 1 = right)")
MACRO_CONFIG_INT(BcMenuUiNewColorPicker, bc_menu_ui_new_color_picker, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use better color picker style when Better UI is enabled")
MACRO_CONFIG_INT(BcMenuUiBetterFont, bc_menu_ui_better_font, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use Better font (Actay Wide Bold) instead of default/TClient font")
MACRO_CONFIG_INT(BcShowStylePicker, bc_show_style_picker, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show one-time menu UI style picker on first launch")
MACRO_CONFIG_INT(BcSettingsNavExpanded, bc_settings_nav_expanded, 0, 0, 7, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Better settings nav expanded groups (bit 0 = DDNet, 1 = TClient, 2 = BestClient)")

// UI Themes
MACRO_CONFIG_INT(BcUiThemes, bc_ui_themes, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable UI Themes")
MACRO_CONFIG_INT(BcUiThemeElement, bc_ui_theme_element, 0, 0, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Selected UI Themes custom element")
MACRO_CONFIG_INT(BcCustomUiBackground, bc_custom_ui_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable colorable UI background")
MACRO_CONFIG_INT(BcCustomUiGradientAnimateSpeed, bc_custom_ui_gradient_animate_speed, 35, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "UI Themes gradient animate speed")
MACRO_CONFIG_INT(BcCustomUiText, bc_custom_ui_text, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI text color")
MACRO_CONFIG_COL(BcCustomUiTextColor, bc_custom_ui_text_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI text color")
MACRO_CONFIG_INT(BcCustomUiTextGradient, bc_custom_ui_text_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI text gradient color")
MACRO_CONFIG_COL(BcCustomUiTextGradientColor, bc_custom_ui_text_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI text gradient color")
MACRO_CONFIG_INT(BcCustomUiTextUseAccent, bc_custom_ui_text_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI text accent color")
MACRO_CONFIG_COL(BcCustomUiTextAccentColor, bc_custom_ui_text_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI text accent color")
MACRO_CONFIG_INT(BcCustomUiCheckbox, bc_custom_ui_checkbox, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI checkbox color")
MACRO_CONFIG_COL(BcCustomUiCheckboxColor, bc_custom_ui_checkbox_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI checkbox color")
MACRO_CONFIG_INT(BcCustomUiCheckboxGradient, bc_custom_ui_checkbox_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI checkbox gradient color")
MACRO_CONFIG_COL(BcCustomUiCheckboxGradientColor, bc_custom_ui_checkbox_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI checkbox gradient color")
MACRO_CONFIG_INT(BcCustomUiCheckboxUseAccent, bc_custom_ui_checkbox_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI checkbox accent color")
MACRO_CONFIG_COL(BcCustomUiCheckboxAccentColor, bc_custom_ui_checkbox_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI checkbox accent color")
MACRO_CONFIG_INT(BcCustomUiScrollbar, bc_custom_ui_scrollbar, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI scrollbar color")
MACRO_CONFIG_COL(BcCustomUiScrollbarColor, bc_custom_ui_scrollbar_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI scrollbar color")
MACRO_CONFIG_INT(BcCustomUiScrollbarGradient, bc_custom_ui_scrollbar_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI scrollbar gradient color")
MACRO_CONFIG_COL(BcCustomUiScrollbarGradientColor, bc_custom_ui_scrollbar_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI scrollbar gradient color")
MACRO_CONFIG_INT(BcCustomUiScrollbarUseAccent, bc_custom_ui_scrollbar_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI scrollbar accent color")
MACRO_CONFIG_COL(BcCustomUiScrollbarAccentColor, bc_custom_ui_scrollbar_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI scrollbar accent color")
MACRO_CONFIG_INT(BcCustomUiButton, bc_custom_ui_button, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI button color")
MACRO_CONFIG_COL(BcCustomUiButtonColor, bc_custom_ui_button_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI button color")
MACRO_CONFIG_INT(BcCustomUiButtonGradient, bc_custom_ui_button_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI button gradient color")
MACRO_CONFIG_COL(BcCustomUiButtonGradientColor, bc_custom_ui_button_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI button gradient color")
MACRO_CONFIG_INT(BcCustomUiButtonUseAccent, bc_custom_ui_button_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI button accent color")
MACRO_CONFIG_COL(BcCustomUiButtonAccentColor, bc_custom_ui_button_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI button accent color")
MACRO_CONFIG_INT(BcCustomUiDropdown, bc_custom_ui_dropdown, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI dropdown color")
MACRO_CONFIG_COL(BcCustomUiDropdownColor, bc_custom_ui_dropdown_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI dropdown color")
MACRO_CONFIG_INT(BcCustomUiDropdownGradient, bc_custom_ui_dropdown_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI dropdown gradient color")
MACRO_CONFIG_COL(BcCustomUiDropdownGradientColor, bc_custom_ui_dropdown_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI dropdown gradient color")
MACRO_CONFIG_INT(BcCustomUiDropdownUseAccent, bc_custom_ui_dropdown_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI dropdown accent color")
MACRO_CONFIG_COL(BcCustomUiDropdownAccentColor, bc_custom_ui_dropdown_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI dropdown accent color")
MACRO_CONFIG_INT(BcCustomUiEditBox, bc_custom_ui_editbox, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI edit box color")
MACRO_CONFIG_COL(BcCustomUiEditBoxColor, bc_custom_ui_editbox_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI edit box color")
MACRO_CONFIG_INT(BcCustomUiEditBoxGradient, bc_custom_ui_editbox_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI edit box gradient color")
MACRO_CONFIG_COL(BcCustomUiEditBoxGradientColor, bc_custom_ui_editbox_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI edit box gradient color")
MACRO_CONFIG_INT(BcCustomUiEditBoxUseAccent, bc_custom_ui_editbox_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI edit box accent color")
MACRO_CONFIG_COL(BcCustomUiEditBoxAccentColor, bc_custom_ui_editbox_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI edit box accent color")
MACRO_CONFIG_INT(BcCustomUiBlock, bc_custom_ui_block, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI settings block color")
MACRO_CONFIG_COL(BcCustomUiBlockColor, bc_custom_ui_block_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI settings block color")
MACRO_CONFIG_INT(BcCustomUiBlockGradient, bc_custom_ui_block_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI settings block gradient color")
MACRO_CONFIG_COL(BcCustomUiBlockGradientColor, bc_custom_ui_block_gradient_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI settings block gradient color")
MACRO_CONFIG_INT(BcCustomUiBlockUseAccent, bc_custom_ui_block_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI settings block accent color")
MACRO_CONFIG_COL(BcCustomUiBlockAccentColor, bc_custom_ui_block_accent_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI settings block accent color")
MACRO_CONFIG_INT(BcCustomUiBlockOpacity, bc_custom_ui_block_opacity, 25, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Settings block background opacity")
MACRO_CONFIG_INT(BcCustomUiMainPanel, bc_custom_ui_main_panel, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI main panel color")
MACRO_CONFIG_COL(BcCustomUiMainPanelColor, bc_custom_ui_main_panel_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI main panel color")
MACRO_CONFIG_INT(BcCustomUiMainPanelGradient, bc_custom_ui_main_panel_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI main panel gradient color")
MACRO_CONFIG_COL(BcCustomUiMainPanelGradientColor, bc_custom_ui_main_panel_gradient_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI main panel gradient color")
MACRO_CONFIG_INT(BcCustomUiMainPanelUseAccent, bc_custom_ui_main_panel_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI main panel accent color")
MACRO_CONFIG_COL(BcCustomUiMainPanelAccentColor, bc_custom_ui_main_panel_accent_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI main panel accent color")
MACRO_CONFIG_INT(BcCustomUiMainPanelOpacity, bc_custom_ui_main_panel_opacity, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Main panel background opacity")
MACRO_CONFIG_INT(BcCustomUiNavTab, bc_custom_ui_nav_tab, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI settings nav tab color")
MACRO_CONFIG_COL(BcCustomUiNavTabColor, bc_custom_ui_nav_tab_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI settings nav tab color")
MACRO_CONFIG_INT(BcCustomUiNavTabGradient, bc_custom_ui_nav_tab_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI settings nav tab gradient color")
MACRO_CONFIG_COL(BcCustomUiNavTabGradientColor, bc_custom_ui_nav_tab_gradient_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI settings nav tab gradient color")
MACRO_CONFIG_INT(BcCustomUiNavTabUseAccent, bc_custom_ui_nav_tab_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI settings nav tab accent color")
MACRO_CONFIG_COL(BcCustomUiNavTabAccentColor, bc_custom_ui_nav_tab_accent_color, 0xFF000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI settings nav tab accent color")
MACRO_CONFIG_INT(BcCustomUiNavTabOpacity, bc_custom_ui_nav_tab_opacity, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Settings nav tab opacity")
MACRO_CONFIG_INT(BcCustomUiBadge, bc_custom_ui_badge, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI badge color")
MACRO_CONFIG_COL(BcCustomUiBadgeColor, bc_custom_ui_badge_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI badge color")
MACRO_CONFIG_INT(BcCustomUiBadgeGradient, bc_custom_ui_badge_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI badge gradient color")
MACRO_CONFIG_COL(BcCustomUiBadgeGradientColor, bc_custom_ui_badge_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI badge gradient color")
MACRO_CONFIG_INT(BcCustomUiBadgeUseAccent, bc_custom_ui_badge_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI badge accent color")
MACRO_CONFIG_COL(BcCustomUiBadgeAccentColor, bc_custom_ui_badge_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI badge accent color")
MACRO_CONFIG_INT(BcCustomUiBind, bc_custom_ui_bind, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI key bind color")
MACRO_CONFIG_COL(BcCustomUiBindColor, bc_custom_ui_bind_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI key bind color")
MACRO_CONFIG_INT(BcCustomUiBindGradient, bc_custom_ui_bind_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI key bind gradient color")
MACRO_CONFIG_COL(BcCustomUiBindGradientColor, bc_custom_ui_bind_gradient_color, 0xFFA0A0A0U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI key bind gradient color")
MACRO_CONFIG_INT(BcCustomUiBindUseAccent, bc_custom_ui_bind_use_accent, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom UI key bind accent color")
MACRO_CONFIG_COL(BcCustomUiBindAccentColor, bc_custom_ui_bind_accent_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Custom UI key bind accent color")

// Browser Utils
MACRO_CONFIG_INT(BcAutoServerListRefresh, bc_auto_server_list_refresh, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically refresh the server browser list while a browser tab is open")
MACRO_CONFIG_INT(BcAutoServerListRefreshSeconds, bc_auto_server_list_refresh_seconds, 10, 1, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto refresh interval for the server browser list in seconds")
MACRO_CONFIG_INT(BcUseShortKogServerName, bc_use_short_kog_server_name, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use short names for E-Gores and KoG servers in browser list")
MACRO_CONFIG_INT(BcShowFinishedMapOnEgo, bc_show_finished_map_on_ego, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show completed EGO maps in the server browser")
MACRO_CONFIG_INT(BcMastersrv, bc_mastersrv, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the BestClient master server mirror for the server browser")
MACRO_CONFIG_INT(BcServerMapPreview, bc_server_map_preview, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a live map preview under the selected server")
MACRO_CONFIG_INT(BrFilterBestclient, br_filter_bestclient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Filter out servers with no BestClient users")

// Client Indicator
MACRO_CONFIG_INT(BcClientIndicatorVersions, bc_client_indicator_versions, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show versions tab in BestClient server browser panel")
MACRO_CONFIG_INT(DbgClientIndicator, dbg_client_indicator, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Debug logging for BestClient indicator (1=verbose, 2=dump all UDP packet bytes sent/received)")
MACRO_CONFIG_INT(BcNameplateClientIndicatorOffsetX, bc_nameplate_client_indicator_offset_x, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Horizontal offset for the client indicator in nameplates")
MACRO_CONFIG_INT(BcNameplateClientIndicatorOffsetY, bc_nameplate_client_indicator_offset_y, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vertical offset for the client indicator in nameplates")
MACRO_CONFIG_INT(BcNameplateVoiceOffsetX, bc_nameplate_voice_offset_x, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Horizontal offset for the voice icon in nameplates")
MACRO_CONFIG_INT(BcNameplateVoiceOffsetY, bc_nameplate_voice_offset_y, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vertical offset for the voice icon in nameplates")
MACRO_CONFIG_INT(BcClientIndicatorInNamePlate, bc_client_indicator_in_name_plate, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show client indicator in name plate")
MACRO_CONFIG_INT(BcClientIndicatorInNamePlateAboveSelf, bc_client_indicator_in_name_plate_above_self, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show client indicator above self")
MACRO_CONFIG_INT(BcClientIndicatorInNamePlateSize, bc_client_indicator_in_name_plate_size, 30, -50, 100, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Client indicator in name plate size")
MACRO_CONFIG_INT(BcClientIndicatorInNamePlateDynamic, bc_client_indicator_in_name_plate_dynamic, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator in nameplates will dynamically change pos")
MACRO_CONFIG_INT(IndicatorVersion, indicator_version, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show BestClient version in name plates")
MACRO_CONFIG_INT(BcClientIndicatorInScoreboard, bc_client_indicator_in_scoreboard, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show client indicator in scoreboard")
MACRO_CONFIG_INT(BcClientIndicatorInSoreboardSize, bc_client_indicator_in_scoreboard_size, 100, -50, 100, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Client indicator in scoreboard size")
MACRO_CONFIG_STR(BcClientIndicatorServerAddress, bc_client_indicator_server_address, 256, "150.241.70.188:8778", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator UDP presence server")
MACRO_CONFIG_STR(BcClientIndicatorBrowserUrl, bc_client_indicator_browser_url, 256, "https://150.241.70.188:8779/users.json", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator browser JSON URL")
MACRO_CONFIG_STR(BcClientIndicatorTokenUrl, bc_client_indicator_token_url, 256, "https://150.241.70.188:8779/token.json", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator token bootstrap URL")
MACRO_CONFIG_STR(BcClientIndicatorSharedToken, bc_client_indicator_shared_token, 256, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator shared token for signed UDP packets")
MACRO_CONFIG_STR(BcClientIndicatorSecretKey, bc_client_indicator_secret_key, 256, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator developer secret key")

// Optimizer
MACRO_CONFIG_INT(BcOptimizer, bc_optimizer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable optimizer features")
MACRO_CONFIG_INT(BcOptimizerDisableParticles, bc_optimizer_disable_particles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable rendering/updating all particles")
MACRO_CONFIG_INT(BcOptimizerDisableQuads, bc_optimizer_disable_quads, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable rendering map quad layers")
MACRO_CONFIG_INT(BcOptimizerDisableHighDetail, bc_optimizer_disable_high_detail, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable high detail map layers (mirrors gfx_high_detail off while optimizer is enabled)")
MACRO_CONFIG_INT(BcOptimizerFpsFog, bc_optimizer_fps_fog, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cull non-map rendering outside a distance limit around the camera")
MACRO_CONFIG_INT(BcOptimizerFpsFogMode, bc_optimizer_fps_fog_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog mode (0=manual radius tiles, 1=by zoom percent)")
MACRO_CONFIG_INT(BcOptimizerFpsFogRadiusTiles, bc_optimizer_fps_fog_radius_tiles, 40, 5, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog manual radius in tiles (tile=32 units)")
MACRO_CONFIG_INT(BcOptimizerFpsFogZoomPercent, bc_optimizer_fps_fog_zoom_percent, 70, 10, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog visible area percent in zoom mode")
MACRO_CONFIG_INT(BcOptimizerFpsFogRenderRect, bc_optimizer_fps_fog_render_rect, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render an outline rectangle showing the FPS fog area")
MACRO_CONFIG_INT(BcOptimizerFpsFogCullMapTiles, bc_optimizer_fps_fog_cull_map_tiles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cull map tile rendering outside the FPS fog area")

// Process priority (from Entity-Client)
MACRO_CONFIG_INT(BcHighProcessPriority, bc_high_process_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set DDNets process priority to high")
MACRO_CONFIG_INT(BcDiscordNormalProcessPriority, bc_discord_normal_process_priority, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set Discord process priority to normal")

// Chat media
MACRO_CONFIG_INT(BcChatMediaPreview, bc_chat_media_preview, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render media previews from chat links")
MACRO_CONFIG_INT(BcChatMediaPhotos, bc_chat_media_photos, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render photo previews from chat links")
MACRO_CONFIG_INT(BcChatMediaGifs, bc_chat_media_gifs, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render GIF and animated media previews from chat links")
MACRO_CONFIG_INT(BcChatMediaContentFilter, bc_chat_media_content_filter, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Allow chat media previews only from configured domains")
MACRO_CONFIG_STR(BcChatMediaAllowedDomains, bc_chat_media_allowed_domains, 512, "tenor.com; imgur.com; giphy.com; gifs.teeworlds.xyz", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Semicolon-separated allowlist for chat media domains")
MACRO_CONFIG_INT(BcChatMediaPreviewMaxWidth, bc_chat_media_preview_max_width, 220, 120, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum width of chat media previews")

// Chat bubbles (above players)
MACRO_CONFIG_INT(BcChatBubbles, bc_chat_bubbles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show chat bubbles above players")
MACRO_CONFIG_INT(BcChatBubblesSelf, bc_chat_bubbles_self, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show chat bubbles above yourself")
MACRO_CONFIG_INT(BcChatBubblesDemo, bc_chat_bubbles_demo, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show chat bubbles in demo playback")
MACRO_CONFIG_INT(BcChatBubbleSize, bc_chat_bubble_size, 20, 20, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Size of chat bubbles")
MACRO_CONFIG_INT(BcChatBubbleShowTime, bc_chat_bubble_showtime, 500, 100, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How long to show chat bubbles (centiseconds)")
MACRO_CONFIG_INT(BcChatBubbleFadeOut, bc_chat_bubble_fadeout, 35, 15, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat bubble fade-out duration (centiseconds)")
MACRO_CONFIG_INT(BcChatBubbleFadeIn, bc_chat_bubble_fadein, 15, 15, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat bubble fade-in duration (centiseconds)")
MACRO_CONFIG_INT(BcChatBubbleAnimation, bc_chat_bubble_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Animate chat bubble stacking movement")
MACRO_CONFIG_INT(BcChatBubbleCustomColors, bc_chat_bubble_custom_colors, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom colors for chat bubbles")
MACRO_CONFIG_COL(BcChatBubbleBgColor, bc_chat_bubble_bg_color, 0x40000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Chat bubble background color")
MACRO_CONFIG_COL(BcChatBubbleTextColor, bc_chat_bubble_text_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Chat bubble text color")
MACRO_CONFIG_COL(BcChatBubbleOutlineColor, bc_chat_bubble_outline_color, 0x80000000U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Chat bubble text outline color")
MACRO_CONFIG_INT(BcChatBubbleRounding, bc_chat_bubble_rounding, 0, 0, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat bubble corner rounding (0 = auto from size)")

// Animations
MACRO_CONFIG_INT(BcAnimations, bc_animations, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle BestClient UI animations")
MACRO_CONFIG_INT(BcModuleUiRevealAnimation, bc_module_ui_reveal_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle settings UI animations (module reveals and tab switch)")
MACRO_CONFIG_INT(BcModuleUiRevealAnimationMs, bc_module_ui_reveal_animation_ms, 180, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Module settings reveal time (in ms)")
MACRO_CONFIG_INT(BcChatAnimation, bc_chat_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle chat animation")
MACRO_CONFIG_INT(BcChatAnimationMs, bc_chat_animation_ms, 300, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat animation time (in ms)")
MACRO_CONFIG_INT(BcChatOpenAnimation, bc_chat_open_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle chat open animation")
MACRO_CONFIG_INT(BcChatOpenAnimationMs, bc_chat_open_animation_ms, 220, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat open animation time (in ms)")
MACRO_CONFIG_INT(BcChatTypingAnimation, bc_chat_typing_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle chat typing animation")
MACRO_CONFIG_INT(BcChatTypingAnimationMs, bc_chat_typing_animation_ms, 180, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat typing animation time (in ms)")
MACRO_CONFIG_INT(BcKillfeedAnimation, bc_killfeed_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle killfeed animation")
MACRO_CONFIG_INT(BcKillfeedAnimationMs, bc_killfeed_animation_ms, 200, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Killfeed animation time (in ms)")
MACRO_CONFIG_INT(BcMainMenuAnimation, bc_main_menu_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle main menu button hover animation")
MACRO_CONFIG_INT(BcMainMenuAnimationSpeed, bc_main_menu_animation_speed, 12, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Main menu hover animation speed")
MACRO_CONFIG_INT(BcChatAnimationType, bc_chat_animation_type, 3, 1, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat animation type")

// Motion blur
MACRO_CONFIG_INT(BcMotionBlur, bc_motion_blur, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable motion blur via previous-frame blending")
MACRO_CONFIG_INT(BcMotionBlurStrength, bc_motion_blur_strength, 50, 0, 95, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strength of motion blur frame blending (0-95%)")

// Edge Info (from RushieClient)
MACRO_CONFIG_COL(RiEdgeInfoColorFreeze, ri_edge_info_color_freeze, 9930605, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Freeze color in edge info")
MACRO_CONFIG_COL(RiEdgeInfoColorKill, ri_edge_info_color_kill, 65461, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Kill color in edge info")
MACRO_CONFIG_COL(RiEdgeInfoColorSafe, ri_edge_info_color_safe, 5594535, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Safe color in edge info")
MACRO_CONFIG_INT(RiEdgeInfoCords, ri_edge_info_cords, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show upper panel of edge info")
MACRO_CONFIG_INT(RiEdgeInfoJump, ri_edge_info_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show lower panel of edge info")
MACRO_CONFIG_INT(RiEdgeInfoPosX, ri_edge_info_pos_x, 50, 0, 100, CFGFLAG_CLIENT, "Legacy edge info pos x; migrated into hud_layout.cfg")
MACRO_CONFIG_INT(RiEdgeInfoPosY, ri_edge_info_pos_y, 56, 0, 100, CFGFLAG_CLIENT, "Legacy edge info pos y; migrated into hud_layout.cfg")

// Legacy HUD layout mirrors from BestClient 2.0 (load-only; migrated into hud_layout.cfg)
MACRO_CONFIG_INT(BcHudMusicPlayerX, bc_hud_music_player_x, 198, -1000, 1000, CFGFLAG_CLIENT, "Legacy music player HUD X")
MACRO_CONFIG_INT(BcHudMusicPlayerY, bc_hud_music_player_y, 0, -1000, 1000, CFGFLAG_CLIENT, "Legacy music player HUD Y")
MACRO_CONFIG_INT(BcHudMusicPlayerScale, bc_hud_music_player_scale, 100, 25, 300, CFGFLAG_CLIENT, "Legacy music player HUD scale")
MACRO_CONFIG_INT(BcHudMusicPlayerLayoutMigrated, bc_hud_music_player_layout_migrated, 0, 0, 5, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player HUD layout anchor migration from BestClient 2.0")
// Voice chat
MACRO_CONFIG_INT(BcVoiceChatEnable, bc_voice_chat_enable, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable integrated voice chat")
MACRO_CONFIG_INT(BcVoiceChatActivationMode, bc_voice_chat_activation_mode, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice activation mode (0 = automatic activation, 1 = push-to-talk)")
MACRO_CONFIG_INT(BcVoiceChatVadThreshold, bc_voice_chat_vad_threshold, 5, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice activation threshold in automatic mode (percent)")
MACRO_CONFIG_INT(BcVoiceChatVadReleaseDelayMs, bc_voice_chat_vad_release_delay_ms, 150, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delay before automatic voice activation turns off (ms)")
MACRO_CONFIG_INT(BcVoiceChatVolume, bc_voice_chat_volume, 100, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice playback volume in percent")
MACRO_CONFIG_INT(BcVoiceChatMicGain, bc_voice_chat_mic_gain, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Microphone gain in percent")
MACRO_CONFIG_INT(BcVoiceChatBitrate, bc_voice_chat_bitrate, 96, 6, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice Opus bitrate in kbps")
MACRO_CONFIG_INT(BcVoiceChatInputDevice, bc_voice_chat_input_device, -1, -1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice input device index (-1 = system default)")
MACRO_CONFIG_INT(BcVoiceChatOutputDevice, bc_voice_chat_output_device, -1, -1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice output device index (-1 = system default)")
MACRO_CONFIG_INT(BcVoiceChatMicMuted, bc_voice_chat_mic_muted, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute voice microphone")
MACRO_CONFIG_INT(BcVoiceChatHeadphonesMuted, bc_voice_chat_headphones_muted, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute voice playback")
MACRO_CONFIG_INT(BcVoiceChatMicCheck, bc_voice_chat_mic_check, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable microphone check (local loopback)")
MACRO_CONFIG_INT(BcVoiceChatInGameOnly, bc_voice_chat_ingame_only, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Only allow voice transmit/playback while the game window is active")
MACRO_CONFIG_INT(BcVoiceChatUseTeam0, bc_voice_chat_use_team0, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Force voice chat to use team 0 even while you are in a team")
MACRO_CONFIG_INT(BcVoiceChatEnableYourGroup, bc_voice_chat_enable_your_group, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "In team0 mode, also include your own team for voice transmit/playback")
MACRO_CONFIG_INT(BcVoiceChatRadiusEnabled, bc_voice_chat_radius_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable local voice radius filter")
MACRO_CONFIG_INT(BcVoiceChatRadiusTiles, bc_voice_chat_radius_tiles, 25, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice radius in tiles when local radius filter is enabled")
MACRO_CONFIG_INT(BcVoiceChatNameplateIcon, bc_voice_chat_nameplate_icon, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show microphone icon in name plates for talking players")
MACRO_CONFIG_STR(BcVoiceChatServerAddress, bc_voice_chat_server_address, 128, "managed", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice server address")
MACRO_CONFIG_STR(BcVoiceChatMutedNames, bc_voice_chat_muted_names, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Comma-separated list of muted voice nicknames (case-insensitive)")
MACRO_CONFIG_STR(BcVoiceChatNameVolumes, bc_voice_chat_name_volumes, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Comma-separated list of voice nickname volumes in percent (name=value, case-insensitive)")
MACRO_CONFIG_STR(BcVoiceModKey, bc_voice_mod_key, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice moderation key (saved for convenience)")

MACRO_CONFIG_INT(BcHudVoiceHudX, bc_hud_voice_hud_x, 0, -1000, 1000, CFGFLAG_CLIENT, "Legacy voice HUD X")
MACRO_CONFIG_INT(BcHudVoiceHudY, bc_hud_voice_hud_y, 100, -1000, 1000, CFGFLAG_CLIENT, "Legacy voice HUD Y")
MACRO_CONFIG_INT(BcHudVoiceHudScale, bc_hud_voice_hud_scale, 100, 25, 300, CFGFLAG_CLIENT, "Legacy voice HUD scale")
MACRO_CONFIG_INT(BcHudVoiceMuteIconsX, bc_hud_voice_mute_icons_x, 136, -1000, 1000, CFGFLAG_CLIENT, "Legacy voice mute icons X")
MACRO_CONFIG_INT(BcHudVoiceMuteIconsY, bc_hud_voice_mute_icons_y, 0, -1000, 1000, CFGFLAG_CLIENT, "Legacy voice mute icons Y")
MACRO_CONFIG_INT(BcHudVoiceMuteIconsScale, bc_hud_voice_mute_icons_scale, 100, 25, 300, CFGFLAG_CLIENT, "Legacy voice mute icons scale")
MACRO_CONFIG_INT(BcHudChatX, bc_hud_chat_x, 5, -1000, 1000, CFGFLAG_CLIENT, "Legacy chat HUD X")
MACRO_CONFIG_INT(BcHudChatY, bc_hud_chat_y, 278, -1000, 1000, CFGFLAG_CLIENT, "Legacy chat HUD Y")
MACRO_CONFIG_INT(BcHudChatScale, bc_hud_chat_scale, 100, 25, 300, CFGFLAG_CLIENT, "Legacy chat HUD scale")
MACRO_CONFIG_INT(BcHudVotesX, bc_hud_votes_x, 0, -1000, 1000, CFGFLAG_CLIENT, "Legacy votes HUD X")
MACRO_CONFIG_INT(BcHudVotesY, bc_hud_votes_y, 60, -1000, 1000, CFGFLAG_CLIENT, "Legacy votes HUD Y")
MACRO_CONFIG_INT(BcHudVotesScale, bc_hud_votes_scale, 100, 25, 300, CFGFLAG_CLIENT, "Legacy votes HUD scale")

// Keystrokes
MACRO_CONFIG_INT(BcKeystrokesStyle, bc_keystrokes_style, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keystrokes style (0 = Classic, 1 = Minecraft)")
MACRO_CONFIG_INT(BcKeystrokesKeyboard, bc_keystrokes_keyboard, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show keyboard keystrokes HUD")
MACRO_CONFIG_INT(BcKeystrokesKeyboardPreset, bc_keystrokes_keyboard_preset, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keyboard keystrokes preset (0 = wasd-minimal, 1 = wasd-full, 2 = micro)")
MACRO_CONFIG_INT(BcKeystrokesMouse, bc_keystrokes_mouse, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show mouse keystrokes HUD")
MACRO_CONFIG_INT(BcKeystrokesMousePreset, bc_keystrokes_mouse_preset, 1, 1, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mouse keystrokes preset (1 = mouse-arrow, 2 = mouse-dot-dot, 3 = mouse-nothing)")
MACRO_CONFIG_INT(BcKeystrokesMcLayout, bc_keystrokes_mc_layout, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Minecraft keystrokes layout (0 = Full, 1 = Only A/D)")
MACRO_CONFIG_INT(BcKeystrokesMcShowLmb, bc_keystrokes_mc_show_lmb, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show LMB in Minecraft keystrokes")
MACRO_CONFIG_INT(BcKeystrokesMcShowRmb, bc_keystrokes_mc_show_rmb, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show RMB in Minecraft keystrokes")
MACRO_CONFIG_INT(BcKeystrokesMcShowSpace, bc_keystrokes_mc_show_space, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show Space in Minecraft keystrokes")
MACRO_CONFIG_INT(BcKeystrokesMcPressedOpacity, bc_keystrokes_mc_pressed_opacity, 92, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Pressed key opacity in Minecraft keystrokes")

// Finish prediction
MACRO_CONFIG_INT(BcFinishPrediction, bc_finish_prediction, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable finish prediction")
MACRO_CONFIG_INT(BcFinishPredictionShowAlways, bc_finish_prediction_show_always, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction even before race start")
MACRO_CONFIG_INT(BcFinishPredictionTimeMode, bc_finish_prediction_time_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction time mode (0=remaining, 1=predicted finish time)")
MACRO_CONFIG_INT(BcFinishPredictionShowTime, bc_finish_prediction_show_time, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction time")
MACRO_CONFIG_INT(BcFinishPredictionShowPercentage, bc_finish_prediction_show_percentage, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction progress percentage")
MACRO_CONFIG_INT(BcFinishPredictionShowMillis, bc_finish_prediction_show_millis, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction milliseconds")
MACRO_CONFIG_INT(BcFinishPredictionConsiderFreezeWalls, bc_finish_prediction_consider_freeze_walls, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Experimental: treat jumpable freeze walls as passable for finish prediction")

// Music Player
MACRO_CONFIG_INT(BcMusicPlayer, bc_music_player, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Music Player HUD element")
MACRO_CONFIG_INT(BcMusicPlayerVisualizerMode, bc_music_player_visualizer_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer mode (0=bottom, 1=center, 2=up)")
MACRO_CONFIG_INT(BcMusicPlayerVisualizerRounding, bc_music_player_visualizer_rounding, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer rounding (0=cube, 200=soft)")
MACRO_CONFIG_INT(BcMusicPlayerVisualizerColumns, bc_music_player_visualizer_columns, 5, 5, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer bar count")
MACRO_CONFIG_INT(BcMusicPlayerColorMode, bc_music_player_color_mode, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player color mode (0=static visualizer, 1=cover visualizer)")
MACRO_CONFIG_COL(BcMusicPlayerStaticColor, bc_music_player_static_color, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Static color for the music player when static color mode is selected")
MACRO_CONFIG_INT(BcMusicPlayerTextScale, bc_music_player_text_scale, 110, 70, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player text scale in percent")
MACRO_CONFIG_INT(BcMusicPlayerShowLyrics, bc_music_player_show_lyrics, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show synchronized song lyrics in the music player")
MACRO_CONFIG_INT(BcMusicPlayerShowCurrentTime, bc_music_player_show_current_time, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show current time tab under lyrics in the music player")

// Focus Mode Settings
MACRO_CONFIG_INT(ClFocusMode, p_focus_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable focus mode to minimize visual distractions")
MACRO_CONFIG_INT(ClFocusModeHideNames, p_focus_mode_hide_names, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide player names in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideEffects, p_focus_mode_hide_effects, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide visual effects in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideHud, p_focus_mode_hide_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide HUD in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideSongPlayer, p_focus_mode_hide_song_player, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide song player in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideUI, p_focus_mode_hide_ui, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide unnecessary UI elements in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideChat, p_focus_mode_hide_chat, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide chat in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideScoreboard, p_focus_mode_hide_scoreboard, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide scoreboard in focus mode")
MACRO_CONFIG_INT(ClFocusModeAutoReply, p_focus_mode_auto_reply, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto reply to pings when focus mode hides chat")
MACRO_CONFIG_STR(ClFocusModeAutoReplyMessage, p_focus_mode_auto_reply_message, 128, "my chat is hidden", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Message to auto reply when focus mode hides chat")

// Corner indicator
MACRO_CONFIG_INT(BcCornerIndicator, bc_corner_indicator, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the corner indicator for off-screen teammates")
MACRO_CONFIG_INT(BcCornerIndicatorOnlyInTeam, bc_corner_indicator_only_in_team, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Only show the corner indicator while in a DDRace team")
MACRO_CONFIG_INT(BcCornerIndicatorShowAlive, bc_corner_indicator_show_alive, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show alive teammates in the corner indicator")
MACRO_CONFIG_INT(BcCornerIndicatorShowFrozen, bc_corner_indicator_show_frozen, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show frozen teammates in the corner indicator")
MACRO_CONFIG_INT(BcCornerIndicatorIndicateLastTeammate, bc_corner_indicator_indicate_last_teammate, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Indicate frozen teammates in the corner indicator when the local player is the last alive")
MACRO_CONFIG_INT(BcCornerIndicatorProximity, bc_corner_indicator_proximity, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scale the corner indicator by distance")
MACRO_CONFIG_INT(BcCornerIndicatorProximityRange, bc_corner_indicator_proximity_range, 2000, 200, 8000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Corner indicator proximity range")
MACRO_CONFIG_INT(BcCornerIndicatorProximityMinSize, bc_corner_indicator_proximity_min_size, 16, 4, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Minimum corner indicator size when scaled by distance")
MACRO_CONFIG_INT(BcCornerIndicatorNinjaFrozen, bc_corner_indicator_ninja_frozen, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the ninja skin for frozen corner indicators")
MACRO_CONFIG_INT(BcCornerIndicatorSizeAlive, bc_corner_indicator_size_alive, 48, 12, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Alive corner indicator size")
MACRO_CONFIG_INT(BcCornerIndicatorSizeFrozen, bc_corner_indicator_size_frozen, 48, 12, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frozen corner indicator size")
MACRO_CONFIG_INT(BcCornerIndicatorLastTeammateSize, bc_corner_indicator_last_teammate_size, 48, 12, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Corner indicator size when indicating the last teammate")
MACRO_CONFIG_INT(BcCornerIndicatorCustomColors, bc_corner_indicator_custom_colors, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use custom colors for the corner indicator")
MACRO_CONFIG_COL(BcCornerIndicatorColorAlive, bc_corner_indicator_color_alive, 0xFFAAFF80U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Alive corner indicator color")
MACRO_CONFIG_COL(BcCornerIndicatorColorFrozen, bc_corner_indicator_color_frozen, 0xFF6BFF8AU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Frozen corner indicator color")
MACRO_CONFIG_COL(BcCornerIndicatorLastTeammateColor, bc_corner_indicator_last_teammate_color, 0xFF6EFF80U, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Corner indicator color when indicating the last teammate")

// Freeze lightning
MACRO_CONFIG_INT(BcFreezeLightning, bc_freeze_lightning, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strike a lightning bolt when a tee gets frozen")
MACRO_CONFIG_COL(BcFreezeLightningColor, bc_freeze_lightning_color, 9371558, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the freeze lightning bolt")
MACRO_CONFIG_INT(BcFreezeLightningHeight, bc_freeze_lightning_height, 400, 100, 900, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Height the freeze lightning bolt comes down from")
MACRO_CONFIG_INT(BcFreezeLightningThickness, bc_freeze_lightning_thickness, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Thickness of the freeze lightning bolt in percent")
MACRO_CONFIG_INT(BcFreezeLightningBranches, bc_freeze_lightning_branches, 3, 0, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Number of side branches of the freeze lightning bolt")
MACRO_CONFIG_INT(BcFreezeLightningImpact, bc_freeze_lightning_impact, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show impact flash, sparks and frost when the lightning hits")
MACRO_CONFIG_INT(BcFreezeLightningShake, bc_freeze_lightning_shake, 35, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Screen shake when the lightning strikes you, 0 to disable")

// Custom hooks
MACRO_CONFIG_INT(BcHookStyle, bc_hook_style, 0, 0, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Effect where the hook grips the world (0 = none, 1 = whirlwind, 2 = black hole, 3 = magic, 4 = fire, 5 = troll, 6 = rainbow, 7 = lightning, 8 = tentacle)")
MACRO_CONFIG_INT(BcHookRope, bc_hook_rope, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the hook itself in the style of the hook effect")
MACRO_CONFIG_INT(BcHookTether, bc_hook_tether, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "A lasso and pulses along the hook when you hook another player")
MACRO_CONFIG_INT(BcHookLassoBox, bc_hook_lasso_box, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Corner brackets on the player your hook holds")
MACRO_CONFIG_INT(BcAirJump, bc_air_jump, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "A ring of light under your feet when you jump in the air, colored like the hook")
MACRO_CONFIG_INT(BcAirJumpHideParticles, bc_air_jump_hide_particles, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide the normal air jump particles while the air jump ring is on")
MACRO_CONFIG_INT(BcHammerSlash, bc_hammer_slash, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "A glowing slash when you swing the hammer, colored like the hook")
MACRO_CONFIG_INT(BcHammerHideParticles, bc_hammer_hide_particles, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide the normal hammer hit particles while the hammer slash is on")
MACRO_CONFIG_INT(BcHookChargeTime, bc_hook_charge_time, 1200, 200, 4000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Milliseconds of holding the hook until its effect is fully grown")
MACRO_CONFIG_INT(BcHookSize, bc_hook_size, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Size of the hook effect in percent")
MACRO_CONFIG_COL(BcHookWindColor, bc_hook_wind_color, 8343024, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the wind lines in the hook whirlwind")
MACRO_CONFIG_INT(BcHookWindBurst, bc_hook_wind_burst, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Burst out a gust of wind when the hook grips")
MACRO_CONFIG_INT(BcHookWindEye, bc_hook_wind_eye, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the turning eye in the middle of the hook whirlwind")
MACRO_CONFIG_INT(BcHookWindDensity, bc_hook_wind_density, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of wind lines in the hook whirlwind in percent")
MACRO_CONFIG_INT(BcHookWindSpin, bc_hook_wind_spin, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Turning speed of the hook whirlwind in percent")
MACRO_CONFIG_INT(BcHookWindThickness, bc_hook_wind_thickness, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Thickness of the wind lines in the hook whirlwind in percent")
MACRO_CONFIG_INT(BcHookWindOpacity, bc_hook_wind_opacity, 100, 10, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Opacity of the wind in the hook whirlwind in percent")
MACRO_CONFIG_INT(BcHookWindLeafAmount, bc_hook_wind_leaf_amount, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of leaves the hook whirlwind carries in percent, 0 for none")
MACRO_CONFIG_INT(BcHookWindDust, bc_hook_wind_dust, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of dust the hook whirlwind stirs up in percent, 0 for none")
MACRO_CONFIG_COL(BcHookHoleColor, bc_hook_hole_color, 1245078, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the black hole's accretion disk")
MACRO_CONFIG_INT(BcHookHoleDisk, bc_hook_hole_disk, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the black hole's accretion disk and lensed light")
MACRO_CONFIG_INT(BcHookHoleStreaks, bc_hook_hole_streaks, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of matter falling into the black hole in percent, 0 for none")
MACRO_CONFIG_INT(BcHookHoleSpin, bc_hook_hole_spin, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Turning speed of the black hole's disk in percent")
MACRO_CONFIG_COL(BcHookMagicColor, bc_hook_magic_color, 12896411, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the hook's spell circle")
MACRO_CONFIG_INT(BcHookMagicRunes, bc_hook_magic_runes, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw runes in the hook's spell circle and chain")
MACRO_CONFIG_INT(BcHookMagicSpin, bc_hook_magic_spin, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Turning speed of the hook's spell circle in percent")
MACRO_CONFIG_INT(BcHookMagicSparkles, bc_hook_magic_sparkles, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of sparkles given off by the hook magic in percent, 0 for none")
MACRO_CONFIG_INT(BcHookRainbowSpeed, bc_hook_rainbow_speed, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How fast the rainbow hook's colors flow in percent")
MACRO_CONFIG_INT(BcHookRainbowGlitter, bc_hook_rainbow_glitter, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of glitter from the rainbow hook in percent, 0 for none")
MACRO_CONFIG_INT(BcHookRainbowRays, bc_hook_rainbow_rays, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Spinning light rays around the rainbow grip")
MACRO_CONFIG_INT(BcHookRainbowWidth, bc_hook_rainbow_width, 100, 50, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Width of the rainbow hook ribbon in percent")
MACRO_CONFIG_COL(BcHookFireColor, bc_hook_fire_color, 982912, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the hook's fire")
MACRO_CONFIG_INT(BcHookFireSmoke, bc_hook_fire_smoke, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Smoke rising from the hook's fire")
MACRO_CONFIG_INT(BcHookFireIntensity, bc_hook_fire_intensity, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of flame in the hook's fire in percent")
MACRO_CONFIG_INT(BcHookFireEmbers, bc_hook_fire_embers, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of embers rising from the hook's fire in percent, 0 for none")
MACRO_CONFIG_COL(BcHookBoltColor, bc_hook_bolt_color, 9240520, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the lightning hook")
MACRO_CONFIG_INT(BcHookBoltJitter, bc_hook_bolt_jitter, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How wildly the lightning hook whips about in percent")
MACRO_CONFIG_INT(BcHookBoltBranches, bc_hook_bolt_branches, 3, 0, 6, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Number of forks splitting off the lightning hook")
MACRO_CONFIG_INT(BcHookBoltSparks, bc_hook_bolt_sparks, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of sparks thrown off where the lightning strikes, 0 for none")
MACRO_CONFIG_INT(BcHookBoltArc, bc_hook_bolt_arc, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Arcs of electricity crawling over the tile the lightning hook holds")
MACRO_CONFIG_COL(BcHookTentacleColor, bc_hook_tentacle_color, 570478, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the tentacle hook")
MACRO_CONFIG_INT(BcHookTentacleWaves, bc_hook_tentacle_waves, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How strongly the tentacle hook writhes in percent")
MACRO_CONFIG_INT(BcHookTentacleThickness, bc_hook_tentacle_thickness, 100, 50, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Thickness of the tentacle hook in percent")
MACRO_CONFIG_INT(BcHookTentacleSuckers, bc_hook_tentacle_suckers, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw suckers along the underside of the tentacle hook")
MACRO_CONFIG_INT(BcHookTentacleSlime, bc_hook_tentacle_slime, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of slime dripping off the tentacle hook, 0 for none")

// Hook hold effect
MACRO_CONFIG_INT(BcGatheredEnergy, bc_gathered_energy, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Energy gathers around you while your hook holds another tee")
MACRO_CONFIG_INT(BcGatheredEnergyAmount, bc_gathered_energy_amount, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of energy motes gathering around you in percent")
MACRO_CONFIG_INT(BcGatheredEnergyAura, bc_gathered_energy_aura, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw the aura and the ground ring of the gathered energy")
MACRO_CONFIG_INT(BcGatheredEnergyBurst, bc_gathered_energy_burst, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Blow the gathered energy apart when the hook comes off the other tee")

// Freeze lifesteal
MACRO_CONFIG_INT(BcFreezePull, bc_freeze_pull, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strands of cold reach out of nearby freeze tiles and strain against you")
MACRO_CONFIG_COL(BcFreezePullColor, bc_freeze_pull_color, 9240520, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the strands of cold")
MACRO_CONFIG_INT(BcFreezePullRange, bc_freeze_pull_range, 140, 60, 260, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How far from the ice the strands start reaching, in pixels")
MACRO_CONFIG_INT(BcFreezePullStrands, bc_freeze_pull_strands, 4, 1, 8, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How many strands of cold reach for you at once")
MACRO_CONFIG_INT(BcFreezePullShield, bc_freeze_pull_shield, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "An arc standing between you and the ice the strands press against")
MACRO_CONFIG_INT(BcFreezePullSparks, bc_freeze_pull_sparks, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of frost shaken off the straining strands, 0 for none")
MACRO_CONFIG_INT(BcFreezePullHookColor, bc_freeze_pull_hook_color, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color the strands like the current hook style")

// Atmosphere
MACRO_CONFIG_INT(BcAtmosphere, bc_atmosphere, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Weather around you")
MACRO_CONFIG_INT(BcWeather, bc_weather, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Weather type (0 = snow, 1 = rain, 2 = fireflies, 3 = dust)")
MACRO_CONFIG_INT(BcWeatherAmount, bc_weather_amount, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of weather in percent")
MACRO_CONFIG_COL(BcWeatherSnowColor, bc_weather_snow_color, 255, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the snow")
MACRO_CONFIG_INT(BcWeatherSnowflakes, bc_weather_snowflakes, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Snow look (0 = dots, 1 = snowflakes)")
MACRO_CONFIG_COL(BcWeatherRainColor, bc_weather_rain_color, 10063569, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the rain")
MACRO_CONFIG_COL(BcWeatherFireflyColor, bc_weather_firefly_color, 3791782, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the fireflies")
MACRO_CONFIG_INT(BcAmbientDust, bc_ambient_dust, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Drift motes of dust through the world for atmosphere")
MACRO_CONFIG_COL(BcAmbientDustColor, bc_ambient_dust_color, 1981660, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color of the ambient dust motes")
MACRO_CONFIG_INT(BcAmbientDustAmount, bc_ambient_dust_amount, 100, 25, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Amount of ambient dust motes in percent")
